const SSID_MAX_LENGTH = 32;
const WIFI_PASSWORD_MAX_LENGTH = 63;
const USERNAME_MAX_LENGTH = 32;
const USER_PASSWORD_MAX_LENGTH = 32;
const DEVICE_NAME_MAX_LENGTH = 32;
const MEAL_NAME_MAX_LENGHT = 32;

export {
  SSID_MAX_LENGTH,
  WIFI_PASSWORD_MAX_LENGTH,
  USERNAME_MAX_LENGTH,
  USER_PASSWORD_MAX_LENGTH,
  DEVICE_NAME_MAX_LENGTH,
  MEAL_NAME_MAX_LENGHT,
};
